version: '3.4'
services:
  db:
    build: test/db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8080
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
  authservice:
    build: test/authservice
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PASSWORD: guest
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_EXCHANGE: mainhub
      PAYLOAD_SECRET: 1234
